### ISSUE TITLE
Issue with "Fix VRC3 Scripts"

### ISSUE THREAD

**Issue by xBri0nc** [FACS01-01/FACS_Utilities#1]
Hello, I'm experiencing a problem with the "Fix VRC3 Scripts" in the FACS_Utilities.  I am trying to recover an avatar from a lost account and trying to fix the VRC3 scripts, but every time I run it through, it ends up with nothing being fixed.  Below is a video for reference.  If there is anything that I am doing wrong or if there is a bug of sorts, it would be greatly appreciated if you can look into it.  Thank you.

https://user-images.githubusercontent.com/75966584/150733174-4ab4afa5-4ac0-47a4-9a4b-0394deac9f3a.mp4

**Comment by FACS01-01** [comment]
You probably didn't extract the ScriptableObjects correctly. Open them with any text editor (notepad) and check if they have any data under the "parameters" or "controls" fields.

**Comment by xBri0nc** [comment]
Just checked and yup, there isn't anything under those.  Looks like something is wrong with my extractor.  Thanks for the help!

**Comment by AgentOperSys** [comment]
I'm in the same boat, have you found the solution yet?
