### ISSUE TITLE
Fix scripts

### ISSUE THREAD

**Issue by ElementRea** [FACS01-01/FACS_Utilities#10]
Hello, here ant there Im having issues of fixing scripts, resulting with this error
![image](https://github.com/FACS01-01/FACS_Utilities/assets/145399195/0b2fd09d-c06b-47a6-bda5-c6424faea735)
There is a workaround, but for that I always have to create fresh project

**Comment by SeyRo1** [comment]
> Hello, here ant there Im having issues of fixing scripts, resulting with this error ![image](https://user-images.githubusercontent.com/145399195/268775503-0b2fd09d-c06b-47a6-bda5-c6424faea735.png) There is a workaround, but for that I always have to create fresh project

What's the workaround plz?

**Comment by ElementRea** [comment]
Create new project

**Comment by SeyRo1** [comment]
> > > Hello, here ant there Im having issues of fixing scripts, resulting with this error ![image](https://user-images.githubusercontent.com/145399195/268775503-0b2fd09d-c06b-47a6-bda5-c6424faea735.png) There is a workaround, but for that I always have to create fresh project
> > 
> > 
> > What's the workaround plz?
> 
> Create new project - thats the "fix"

then what? I created a new project and dragged the assets into the new it gave me the same error

**Comment by ElementRea** [comment]
> SeyRo1

Oh .. well at that point I have no idea. I had to create new project and then it worked. Had to be completely clean project and I have imported 1 avi which give this an error there and I was able to fix it

**Comment by FACS01-01** [comment]
should be fixed in latest release
