### ISSUE TITLE
fix FACS load bundle

### ISSUE THREAD

**Issue by jyez66** [FACS01-01/FACS_Utilities#11]
hi everyone, i hope everything is ok with you, i need your help, i'm trying to finish an avatar and i need "facs load bundle" but this error appears and it won't load the 'avatar in .vrca, if you know how to do it, don't hesitate, thank you (if anyone has the TI:NI avatar already made I want it XD)

PS: sorry for my bad english, im frensh 

![image_2023-11-08_160131615](https://github.com/FACS01-01/FACS_Utilities/assets/150267483/d134d0a8-94a8-4dcc-8259-e8a6594d11b1)

**Comment by nofuyyo** [comment]
Happen the same to me, any solution?

**Comment by Luke5265** [comment]
i have the same issue

**Comment by FACS01-01** [comment]
because of the recent change of Unity version used by VRC, the new bundles saved in cache are kinda incompatible with the current Unity Editor.
i haven't looked into this yet, but there may be a workaround that would require an extra tool/program in between.

**Comment by Dean2k** [comment]
> hi everyone, i hope everything is ok with you, i need your help, i'm trying to finish an avatar and i need "facs load bundle" but this error appears and it won't load the 'avatar in .vrca, if you know how to do it, don't hesitate, thank you (if anyone has the TI:NI avatar already made I want it XD)
> 
> PS: sorry for my bad english, im frensh
> 
> ![image_2023-11-08_160131615](https://user-images.githubusercontent.com/150267483/281446758-d134d0a8-94a8-4dcc-8259-e8a6594d11b1.png)

Try running the avatar through my tool https://github.com/Dean2k/FACSVRCA/releases/tag/1.0.0.0 then load the outputted file in FACS load bundle.
