### ISSUE TITLE
Failed to load AssetBundle

### ISSUE THREAD

**Issue by AxoRamsay** [FACS01-01/FACS_Utilities#12]
![Bild_2024-01-03_143551556](https://github.com/FACS01-01/FACS_Utilities/assets/128068047/da677f82-882e-4d04-8b4e-a11cdcb3ad89)
Everytime i try to load the bundle source i get this error and cant figure out why i followed multiple guides but none worked for me

**Comment by Lucario4LyfeYT** [comment]
open it in unity version 2022.3.6f1
