### ISSUE TITLE
Fix scripts

### ISSUE THREAD

**Issue by girthgod666** [FACS01-01/FACS_Utilities#13]
i see that this issue has been shown before twice but when tring to use fix scripts the same error message come back, iv tried adding the .scripts folder before, am i missing anything, if so could i possibly get an updated way around this issue and or assistance thank you

**Comment by girthgod666** [comment]
![image](https://github.com/FACS01-01/FACS_Utilities/assets/119830232/ca5c6a84-9634-42df-9f60-470889e51ce0)
 this one to be exact

**Comment by FACS01-01** [comment]
should be fixed in latest release
