### ISSUE TITLE
fix scripts 

### ISSUE THREAD

**Issue by lumrei** [FACS01-01/FACS_Utilities#14]
keep getting "[Fix Scripts] There is no ".Scripts" folder inside the selected folder."
before this i was getting "there's no .monoscripts" but i renamed the monobehavior folder and now thats what i keep getting

**Comment by FACS01-01** [comment]
The "Scripts" folder is a folder created while ripping with AssetRipper or derivated tool.
Before importing the ripped "Assets" folder, you have to rename "Scripts" to ".Scripts" in order to use Fix Scripts properly.
The "Scripts" and "Monobehavior" folders are different.
