### ISSUE TITLE
hi I have a question

### ISSUE THREAD

**Issue by jonathanjean** [FACS01-01/FACS_Utilities#2]
I saw facs utilities can fix parameters or menu like scriptable objects. I see no fixing notification from the program and it is not fixed. 'Fix VRC3 Scripts' is no longer working?
![aa](https://user-images.githubusercontent.com/28839790/160265224-5bcc2024-89f7-4278-af2f-401b71d9068b.png)

**Comment by LargestBoi** [comment]
It only works with avatars extracted with ARES

**Comment by jonathanjean** [comment]
thank you

**Comment by jonathanjean** [comment]
Could you delete this issue?

**Comment by LargestBoi** [comment]
y?

**Comment by jonathanjean** [comment]
My friend found out i am using it through this issue

**Comment by LargestBoi** [comment]
XD
