### ISSUE TITLE
Batch Load Bundles "VRCA" parser is case sensitive

### ISSUE THREAD

**Issue by DarkShoro** [FACS01-01/FACS_Utilities#5]
### **Current Behavior**
FACS Only load files with the ".vrca" extension and doesn't take into account file likes ".Vrca", ".vrCa" or ".VRCA"

### **Expected Behavior**
FACS Should load every vrca files case insensitively.

### **Steps to Reproduce**

- Take a random VRCA
- Rename it so the extension contain a CASE
- Try to load it with the **Batch Load Bundles**

**Comment by FACS01-01** [comment]
Tool has been discontinued
