### ISSUE TITLE
panel not showing up

### ISSUE THREAD

**Issue by Wonkiero** [FACS01-01/FACS_Utilities#6]
when i try to upload facs utilities to unity, it should pop up on the top, but it's not doing it 
![Immagine 2023-04-09 161207](https://user-images.githubusercontent.com/84275795/230777737-3f2854c4-5345-4bc8-b61a-b58816292fd1.png)

and i have also one error on the bottom 
![Immagine 2023-04-09 161300](https://user-images.githubusercontent.com/84275795/230777774-cb90d3a1-493d-4425-9d82-74bf0b2a6064.png)

**Comment by FACS01-01** [comment]
Your project was broken before importing the Utilities, and that won't allow the new scripts to compile and run
