### ISSUE TITLE
[Fix Scripts] There is no ".MonoScript" folder inside the selected folder, or it doesn't contain any .meta file.

### ISSUE THREAD

**Issue by denis-hik** [FACS01-01/FACS_Utilities#7]
[Fix Scripts] There is no ".MonoScript" folder inside the selected folder, or it doesn't contain any .meta file.

**Comment by SounaVR** [comment]
just rename the Scripts folder to ".Scripts"

**Comment by NovaUndetected** [comment]
Yeah, same problem

**Comment by Luois45** [comment]
> [Fix Scripts] There is no ".MonoScript" folder inside the selected folder, or it doesn't contain any .meta file.

Same problem over here

> just rename the Scripts folder to ".Scripts" with the explorer before importing the ripped assets

Doesn't fix it for me.

**Comment by SounaVR** [comment]
I don't use that way anymore sry guys

**Comment by Luois45** [comment]
It is still working if you rename the Shader folder to .Shader and import it as well into unity.

**Comment by realdoomsboygaming** [comment]
I think its because if you make it so it automatically fixes the scripts within SARS that file no longer exists when extracting the avatar into a unitypackage.
